--CREATE TABLE virtualpiggy_order(
--	ORDER_ID		VARCHAR2(254)	NOT NULL REFERENCES DCSPP_ORDER(ORDER_ID),
--	VP_TOKEN		VARCHAR2(254)   NOT NULL,
--	VP_LOGIN_ID		VARCHAR2(254)	NULL,
--	VP_CHILD_ID		VARCHAR2(254)	NULL,
--	PRIMARY KEY(ORDER_ID)
--);

CREATE TABLE virtualpiggy_payment(
	PAYMENT_GROUP_ID		VARCHAR2(40)		NOT NULL REFERENCES DCSPP_PAY_GROUP(PAYMENT_GROUP_ID),
	VP_TOKEN				VARCHAR2(254)   NULL,
	VP_CHILD_ID				VARCHAR2(254)	NULL,
	VP_TRANS_DESC			VARCHAR2(254)	NULL,
	VP_PAYMENT_ACCOUNT_ID	VARCHAR2(254)	NULL,
	PRIMARY KEY(PAYMENT_GROUP_ID)
);

CREATE TABLE virtualpiggy_payment_status(
	STATUS_ID				VARCHAR2(40) NOT NULL	REFERENCES DCSPP_PAY_STATUS(STATUS_ID),
	VP_TRANSACTION_STATUS	VARCHAR2(40) NULL,
	PRIMARY KEY(STATUS_ID)
);